# Ejercicio 6 de la Sección 1.2.7

## Dados los vectores  $\vec{a}$, $\vec{b}$, $\vec{c}$, $\vec{d}$


In [1]:
import sympy as sp
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([3,2,1])
d = np.array([6,5,4])

## a) Encuentre: $\vec{a}$ + $\vec{b}$ + $\vec{c}$ + $\vec{d}$  ;  $\vec{a}$ + $\vec{b}$ - $\vec{c}$ - $\vec{d}$  ;  $\vec{a}$ - $\vec{b}$ + $\vec{c}$ - $\vec{d}$  ;  - $\vec{a}$ + $\vec{b}$ - $\vec{c}$ + $\vec{d}$

In [35]:
c1 = a + b + c + d 
print(f'a + b + c + d: {c1}')
c2 = a + b -c - d
print(f'a + b - c - d: {c2}')
c3 = a - b + c - d
print(f'a - b + c - d: {c3}')
c4 = -a + b - c + d
print(f'a + b - c + d: {c4}')

a + b + c + d: [14 14 14]
a + b - c - d: [-4  0  4]
a - b + c - d: [-6 -6 -6]
a + b - c + d: [6 6 6]


## b) El angulo entre los vectores $\vec{a}$, $\vec{b}$, $\vec{c}$, $\vec{d}$  y los vectores $\hat{e}_{1}$,  $\hat{e}_{2}$, $\hat{e}_{3}$ (osea los cosenos directores)

In [32]:
#Cosenos directores del vector a
cosdir1_e1_a = np.degrees(np.arccos(a[0]/np.linalg.norm(a)))
print(f'el angulo #1 del coseno director de a con e1 es: {cosdir1_e1_a} grados')
cosdir1_e2_a = np.degrees(np.arccos(a[1]/np.linalg.norm(a)))
print(f'el angulo #2 del coseno director de a con e2 es: {cosdir1_e2_a} grados')
cosdir1_e3_a = np.degrees(np.arccos(a[2]/np.linalg.norm(a)))
print(f'el angulo #3 del coseno director de a con e3 es: {cosdir1_e3_a} grados')
print('\n')

#Cosenos directores del vector b
cosdir1_e1_b = np.degrees(np.arccos(b[0]/np.linalg.norm(b)))
print(f'el angulo #1 del coseno director de b con e1 es: {cosdir1_e1_b} grados')
cosdir1_e2_b = np.degrees(np.arccos(b[1]/np.linalg.norm(b)))
print(f'el angulo #2 del coseno director de b con e2 es: {cosdir1_e2_b} grados')
cosdir1_e3_b = np.degrees(np.arccos(b[2]/np.linalg.norm(b)))
print(f'el angulo #3 del coseno director de b con e3 es: {cosdir1_e3_b} grados')
print('\n')

#Cosenos directores del vector c
cosdir1_e1_c = np.degrees(np.arccos(c[0]/np.linalg.norm(c)))
print(f'el angulo #1 del coseno director de c con e1 es: {cosdir1_e1_c} grados')
cosdir1_e2_c = np.degrees(np.arccos(c[1]/np.linalg.norm(c)))
print(f'el angulo #2 del coseno director de c con e2 es: {cosdir1_e2_c} grados')
cosdir1_e3_c = np.degrees(np.arccos(c[2]/np.linalg.norm(c)))
print(f'el angulo #3 del coseno director de c con e3 es: {cosdir1_e3_c} grados')
print('\n')

#Cosenos directores del vector d
cosdir1_e1_d = np.degrees(np.arccos(d[0]/np.linalg.norm(d)))
print(f'el angulo #1 del coseno director de d con e1 es: {cosdir1_e1_d} grados')
cosdir1_e2_d = np.degrees(np.arccos(d[1]/np.linalg.norm(d)))
print(f'el angulo #2 del coseno director de d con e2 es: {cosdir1_e2_d} grados')
cosdir1_e3_d = np.degrees(np.arccos(d[2]/np.linalg.norm(d)))
print(f'el angulo #3 del coseno director de d con e3 es: {cosdir1_e3_d} grados')
print('\n')

el angulo #1 del coseno director de a con e1 es: 74.498640433063 grados
el angulo #2 del coseno director de a con e2 es: 57.688466762576155 grados
el angulo #3 del coseno director de a con e3 es: 36.69922520048988 grados


el angulo #1 del coseno director de b con e1 es: 62.88085722661892 grados
el angulo #2 del coseno director de b con e2 es: 55.26351871874204 grados
el angulo #3 del coseno director de b con e3 es: 46.86156238032894 grados


el angulo #1 del coseno director de c con e1 es: 36.69922520048988 grados
el angulo #2 del coseno director de c con e2 es: 57.688466762576155 grados
el angulo #3 del coseno director de c con e3 es: 74.498640433063 grados


el angulo #1 del coseno director de d con e1 es: 46.86156238032894 grados
el angulo #2 del coseno director de d con e2 es: 55.26351871874204 grados
el angulo #3 del coseno director de d con e3 es: 62.88085722661892 grados




## c) Magnitud de los vectores $\vec{a}$, $\vec{b}$, $\vec{c}$, $\vec{d}$  

In [34]:
norm_a = np.linalg.norm(a)
print(f'Norma de a {norm_a}')
norm_b = np.linalg.norm(b)
print(f'Norma de b {norm_b}')
norm_c = np.linalg.norm(c)
print(f'Norma de c {norm_c}')
norm_d = np.linalg.norm(d)
print(f'Norma de d {norm_d}')

Norma de a 3.7416573867739413
Norma de b 8.774964387392123
Norma de c 3.7416573867739413
Norma de d 8.774964387392123


## d) Angulo entre los vectores $\vec{a}$ y $\vec{b}$  y entre  $\vec{c}$ y $\vec{d}$  

In [45]:
theta1 = np.degrees(np.arccos(np.dot(a,b)/((np.linalg.norm(a))*(np.linalg.norm(b)))))
print(f'el angulo entre a y b es: {theta1} grados')

theta2 = np.degrees(np.arccos(np.dot(c,d)/((np.linalg.norm(c))*(np.linalg.norm(d)))))
print(f'el angulo entre c y d es: {theta2} grados')


el angulo entre a y b es: 12.933154491899135 grados
el angulo entre c y d es: 12.933154491899135 grados


## e) Proyeccion entre los vectores $\vec{a}$ y $\vec{b}$  

In [47]:
Proy_a_b = (np.dot(a,b)*(a)) / (np.linalg.norm(b)**2)
Proy_a_b

array([0.41558442, 0.83116883, 1.24675325])

## f) ¿Son los vectores $\vec{a}$  ,  $\vec{b}$  ,  $\vec{c}$  ,  $\vec{d}$  coplanares?

#### Primero tenemos que formar 3 vectores apartir de el vector a

In [49]:
x = b - a
y = c - a
z = d - a

print(f'x: {x}')
print(f'x: {y}')
print(f'x: {z}')


x: [3 3 3]
x: [ 2  0 -2]
x: [5 3 1]


#### Para determinar si estos son coplanares se puede sacando el determinante de estos

In [63]:
sis = np.array([x,y,z])
print(sis)
det =np.linalg.det(sis)
print(f'Con un determinante = {int(det)}')

[[ 3  3  3]
 [ 2  0 -2]
 [ 5  3  1]]
Con un determinante = 0


## g) Encuentre ($\vec{a}$  +  $\vec{b}$)  *  ($\vec{c}$  +  $\vec{d}$) 

In [64]:
c  = (a + b) 
c2 = (c + d)
res = np.dot(c,c2)
res

256

## h) Encuentre los productos ($\vec{a}$  x  $\vec{b}$)  ,  ($\vec{b}$  x  $\vec{c}$)  ,  ($\vec{c}$  x  $\vec{d}$) y los angulos que forman con el vector  $\vec{d}$

In [68]:
# c1 = a x b y su angulo con d
c1 = np.cross(a,b)
c1_angulo = np.degrees(np.arccos(np.dot(c1,d)/((np.linalg.norm(c1))*(np.linalg.norm(d)))))
print(c1)
print(c1_angulo)
# c2 = b x c y su angulo con d
c2 = np.cross(b,a)
c2_angulo = np.degrees(np.arccos(np.dot(c2,d)/((np.linalg.norm(c2))*(np.linalg.norm(d)))))
print(c2)
print(c2_angulo)
# c2 = c x d y su angulo con d
c3 = np.cross(c,d)
c3_angulo = np.degrees(np.arccos(np.dot(c3,d)/((np.linalg.norm(c3))*(np.linalg.norm(d)))))
print(c3)
print(c3_angulo)

[-3  6 -3]
90.0
[ 3 -6  3]
90.0
[-17  34 -17]
90.0


## i) Encuentre  $\vec{c}$  *  ($\vec{a}$  x  $\vec{b}$)

In [69]:
res = np.dot(c,np.cross(a,b))
res

0